### ISSUE TITLE
FIX: Incorrect Deleting Item from a Wishlist

### ISSUE THREAD

**Issue by ahighmoon** [CSCI-GA-2820-FA24-001/wishlists#51]

**Comment by HelenZhou2400** [comment]
Deleting an Item from a Wishlist was implemented incorrectly. While it is OK to return 404_NOT_FOUND if the Wishlist wasn't found, it is not OK to return 404_NOT_FOUND if the Item isn't found. It should always return 204_NO_CONTENT so that it is idempotent. If I call delete item two time in a row on a Wishlist, it should return the same status both times.
